theme: minima

title: "Chinese Postpunk Anthology"
author: "Toma Verlaine"
description: "Chinese Postpunk Anthology is a collection of notes,
translations, and fragments on independent music scenes
across China, with a focus on post-punk and its margins."
plugins:
  - jekyll-feed

feed:
  excerpt_only: true