title: "CHINESE POSTPUNK ANTHOLOGY"
author: "Toma Verlaine"
description: "Chinese Postpunk Anthology is a collection of notes,
translations, and fragments on independent music scenes
across China, with a focus on post-punk and its margins."
permalink: /:year-:month-:day-:title/
plugins:
  - jekyll-feed

feed:
  excerpt_only: true
languages: [en, zh, ja]
default_lang: en
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      ref: ""         # 単言語投稿は空 